FROM hypriot/rpi-alpine
MAINTAINER matt@tuma.cc

RUN apk update
RUN apk add ruby ruby-dev ruby-bundler build-base

ENV TZ=America/Chicago
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY ./Gemfile ./
COPY ./.gemrc ./
RUN bundle install
